### ISSUE TITLE
No output on Node.js

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#103]
Today I tried to use logdown v3.2.2 but when running my script I don't see log output from logdown. Am I doing something wrong?

```javascript
const logdown = require('logdown');

const logger = logdown('MyLoggerPrefix', {
  logger: console,
  prefixColor: '#FF0000'
});

logger.log('My log message with logdown.');
console.log('My log message with console.log');
```

**Screenshot**

![Screenshot](https://user-images.githubusercontent.com/469989/34340118-46a60cd8-e97e-11e7-974f-c588eba2ea09.png)

**Runkit**

- https://runkit.com/bennyn/59feff09617b520016eb4221

**Comment by bennyn** [comment]
@SleepWalker Do you have an idea why this happens?

**Comment by SleepWalker** [comment]
Hi, @bennyn. This is because you haven't set `DEBUG` or `NODE_DEBUG` env var (e.g. `$ DEBUG=* node ./index.js`). As I know this currently expected behavior.

You can try the following snippet to see the difference:

```js
const logdown = require('logdown');

process.env.DEBUG='*';
logdown._setPrefixRegExps(); // this is a hack to force logdown re-parse env vars at runtime

const logger = logdown('MyLoggerPrefix', {
  logger: console,
  prefixColor: '#FF0000'
});

logger.log('My log message with logdown.');
console.log('My log message with console.log');
```

I think, we can discuss this behavior if it seems to be not that clear or expected

**Comment by bennyn** [comment]
Thanks @SleepWalker for clarification! I'm very surprised that a `DEBUG` environment variable needs to be set beforehand. Is that there to mimic the behaviour of [debug.js](https://github.com/visionmedia/debug)? 

I mean, the code clearly says that a logger should be created which logs to the `console` output and with logdown v2.2.0 I was able to log things without setting an env var and I really liked it because it made things easy.

**Comment by SleepWalker** [comment]
@bennyn yep, the behaviour was changed in magor version since https://github.com/caiogondim/logdown.js/commit/65bf056ae46950f1fa11eec337d00a9f7322201b

**Comment by caiogondim** [comment]
The behavior was changed to mimic [debuglog](https://nodejs.org/docs/latest/api/util.html#util_util_debuglog_section) which is the NodeJS debugger utility. debug.js mimics it.

As a pattern, we usually set the env before a script, e.g.: https://github.com/reactjs/redux/blob/master/package.json#L26

**Comment by bennyn** [comment]
@caiogondim & @SleepWalker Thanks for clarifying how logging on Node.js with logdown works. I got it running now. 😃 

I am using [cross-env](https://github.com/kentcdodds/cross-env) to set environment variables in my Node scripts. Here is the script definition from my `package.json` file:

```
"dev": "yarn dist:dev && cross-env DEBUG=* node dist/index.js"
```

And here is some demo code (for reference):

```typescript
const logdown = require('logdown')

const logger: any = logdown('MyLogger', {
  logger: console,
  prefixColor: '#0667D0'
})

console.log('env', process.env.DEBUG) // prints "env *"
this.logger.log('HEY!') // prints "MyLogger HEY!"
```

Closing this issue now. 🎉

**Comment by bennyn** [comment]
Just for the record... 

If you want to **enable logging in the browser**, you have to do the following:

```html
<script src="./bower_components/logdown/dist/logdown.js"></script>

<script>
  // Activating console.log logging for all namespaces (wildcard)
  window.localStorage.debug = '*';

  const logger = window.logdown('Demo');
  logger.log('HEY!');
</script>
```
