### ISSUE TITLE
Run tests on SauceLabs

### ISSUE THREAD

**Issue by caiogondim** [caiogondim/logdown.js#11]

**Comment by bennyn** [comment]
@caiogondim Should we register for https://saucelabs.com/open-source ?

**Comment by caiogondim** [comment]
At the time the experience on setting SauceLabs was very bad.
We can try it again.

**Comment by bennyn** [comment]
I have a SauceLabs Karma configuration somewhere... Will report back once I found it. Maybe it helps setting it up. 

I also like BrowserStack pretty much (we use them at [Wire](https://wire.com/)). We can apply there for "Open Source": https://www.browserstack.com/contact?ref=open_source#sales

**Comment by bennyn** [comment]
FYI: I just wrote to BrowserStack and asked if they are willing to support us.

I also found a Karma configuration file where I had BrowserStack setup & running, so we can get up to speed with BrowserStack very quickly:
https://github.com/bennyn/chacha20-js/blob/bb5b4bdea9d02921a7218674a95989b4e69791d5/conf/grunt/options/nightwatch.js

**Comment by caiogondim** [comment]
I'm still thinking about moving to Jest and forget about E2E testing.

**Comment by bennyn** [comment]
Ok. I have to check what's so special about Jest. How does it run tests on Browser engines? Does it use an approach like [PhantomJS](http://phantomjs.org/)?

**Comment by caiogondim** [comment]
It does not run.
We would ditch end-to-end testing and test only correctness (expectations) of algorithm.

The way we are testing don't bring much safety, since we only test if `console.X` was called with the right amount of arguments. That can be done with Jest and is much more simpler.

**Comment by caiogondim** [comment]
Ditching this tasks
