### ISSUE TITLE
Printing loglevel as prefix

### ISSUE THREAD

**Issue by tonyxiao** [caiogondim/logdown.js#151]
Is it possible to use prefix log level before statements?

**Comment by caiogondim** [comment]
Didn't get it.
Can you make an example?

**Comment by tonyxiao** [comment]
As in making the log statement show up as `[DEBUG] my statement`.

**Comment by tonyxiao** [comment]
Assuming it's debug level log

**Comment by caiogondim** [comment]
Isn't it the current behavior?
https://github.com/caiogondim/logdown.js#browser-devtools-dark

Or you mean to show the method name?
```js
const logger = logdown('bar')
logger.log('foo') // => [LOG] foo
logger.debug('foo') // => [DEBUG] foo
```

**Comment by tonyxiao** [comment]
<img width="921" alt="cloudapp annotation 2018-03-28 at 14 38 37 png" src="https://user-images.githubusercontent.com/696842/38057889-c0bf2c2e-3295-11e8-81b0-c714520d8ccf.png">
Hmm I was thinking of something like this - actually adding the word `[DEBUG]` as part of the log line (sometimes I get confused by color)

**Comment by caiogondim** [comment]
Understood.

The idea is to keep core as simple as possible and move new features to a plugin system.
If you create a repo and give me commit access we can work on this together. 
It's straightforward.

**Comment by tonyxiao** [comment]
Ah got it. Ok thanks! I'll take a look first and ping you if anything comes up :)

**Comment by caiogondim** [comment]
Just created a package that does that https://github.com/caiogondim/logdown-print-method-name.js
The idea is to leave logdown as simple as possible, and just add plugins on top of it.

Let me know if that solves your problem.

**Comment by tonyxiao** [comment]
Ah awesome, thanks!!

**Comment by tonyxiao** [comment]
Will give it a try!
