### ISSUE TITLE
Logdown in Angularjs

### ISSUE THREAD

**Issue by kcijeziefairsailcom** [caiogondim/logdown.js#20]
How can I use this in Angugalrjs 1.2+ App??

**Comment by caiogondim** [comment]
Can't you call `console.log` form Angular?
If so, it should be ok to use Logdown.

You tested?
Can you show some snippet of code so i can test?

**Comment by caiogondim** [comment]
@kcijeziefairsailcom Still waiting a reply from you, so we can solve your issue.

**Comment by kcijeziefairsailcom** [comment]
Hi Cai,

I got it working with angularjs but I keep getting 'undefined' along with the log message. See snippet below:

--------index.html--------
<html>
    <head>
        <title>Test App</title>
    </head>
    <body ng-app="testApp">
        <div class="nav" ng-controller="HomeController">
            <h1>{{ title }}</h1>
            <input type="text" ng-model="title" />
        </div>
        <script src="angular.js"></script>
        <script src="app.js"></script>
		<script src="logdown.js"></script>
		<script src="devtools-detect.js"></script>
    </body>
</html>


---------------------app.js-----------------------------

function HomeCtrl($scope) {
	var demo = new Logdown({prefix: 'demo'});
    $scope.title = "Welcome to angularjs";
    var x = [2,8,9,6,5];
    console.log(Math.max.apply(null, x));
    var sum = 0;
    for(var i in x){
       sum += x[i]; 
    }
    console.log(sum/x.length);
	demo.log(sum/x.length);
}

angular
    .module('testApp', [])
    .controller('HomeController', HomeCtrl);


And in my chrome console, I get - 
app.js:7               9
app.js:12             6
logdown.js:9        demo 6 undefined

**Comment by caiogondim** [comment]
Can you double check if you are running the latest version?
I fixed that bug.

**Comment by kcijeziefairsailcom** [comment]
Still there - demo 6 undefined from @version v1.1.1

**Comment by caiogondim** [comment]
It should be fixed now in the 1.1.2 version.
Can you check again/

**Comment by caiogondim** [comment]
@kcijeziefairsailcom Would you mind testing it again?

**Comment by bennyn** [comment]
@kcijeziefairsailcom Could your problem be solved?

**Comment by caiogondim** [comment]
Every issue with more than 30 days without reply will be closed.
