### ISSUE TITLE
Using "console.info" does not work with logdown on old browsers

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#212]
Older browsers (like Chrome 49) have support for `console.info`. Unfortunately logdown blocks them from using it and throws an error instead.

**Screenshot:**

![uncaught-type-error](https://user-images.githubusercontent.com/469989/43469625-e136d1ec-94e6-11e8-85a8-77a27cda7e4e.png)

**How to reproduce:**

1. Use Chrome 49
1. Open Logdown demo page: https://caiogondim.github.io/logdown.js
1. Execute the following code within the JS console

```js
var a = new logdown('test')
a.info('')
```

**Comment by caiogondim** [comment]
We should just delegate to `console`.
That's a bug.

**Comment by caiogondim** [comment]
Pushed a potential fix.
