### ISSUE TITLE
feat: Add setDefaultEnabled

### ISSUE THREAD

**Issue by SleepWalker** [caiogondim/logdown.js#217]
On some environments you want to have logs always to be enabled (e.g. in dev environment).

I propose to add method `logdown.setDefaultEnabled(boolean)` to allow overriding which value will be set for `state.isEnabeld` in case, when no `NODE_DEBUG` or `localStorage.debug` variable set.

I can submit PR, if the feature will be accepted :)

**Comment by caiogondim** [comment]
I think we should keep the core as simple as possible.

You could achieve that feature through inheritance:
```js
const Logdown = require('logdown')

class MyLogger extends Logdown {
  constructor(...args) {
    super(...args)
    
    if (window.something) {
      this.state.isEnabled = true;
    }
  }
}
```

**Comment by SleepWalker** [comment]
Ok. Currently, I've monkey patched Logdown._getEnableState. but the problem is, that the method begins from underscore, which means, that it is not supposed to be used externaly
