### ISSUE TITLE
`transports` is a ready-only property - TypeScript 2.3.4

### ISSUE THREAD

**Issue by AhsanAyaz** [caiogondim/logdown.js#218]
```bash
typescript: src/constants/logger.ts, line: 2 
            Cannot assign to 'transports' because it is a constant or a read-only property. 

       L1:  import logdown from 'logdown';
       L2:  logdown.transports = [ loggerTransport ];
```

Unable to assign transports to logdown.transports as it is a constant according to the types. Just needs updating the types I believe.

**Comment by j-walker23** [comment]
This looks fixed in the package i downloaded.
Type file shows `  let transports: TransportFunction[];`

**Comment by AhsanAyaz** [comment]
@j-walker23 that's accurate.
https://github.com/caiogondim/logdown.js/pull/219 Fixed this issue.
