### ISSUE TITLE
Maybe I miss something but demo page does not work.

### ISSUE THREAD

**Issue by veremeenko** [caiogondim/logdown.js#29]
Demo page does not work in Chrome/IE10.

**Comment by rscafi** [comment]
You need to open your dev tools on *docked* mode in order to the script detect it and start the demo.

**Comment by caiogondim** [comment]
@veremeenko Could you confirm that the demo is working on IE10 with DevTools on docked mode?
So we can close this issue.

**Comment by veremeenko** [comment]
![image](https://cloud.githubusercontent.com/assets/1991745/7514651/11215f48-f4c8-11e4-9b60-581794f6f9e3.png)

**Comment by caiogondim** [comment]
Seems like a bug on https://github.com/sindresorhus/devtools-detect
Will investigate

**Comment by rictorres** [comment]
> Seems like IE doesn't support CustomEvent. You can polyfill it by placing this https://raw.githubusercontent.com/d4tocchini/customevent-polyfill/master/CustomEvent.js before devtools-detect.

from https://github.com/sindresorhus/devtools-detect/issues/14

**Comment by bennyn** [comment]
@rictorres Thanks for tracking it down.

I checked [CustomEvent on caniuse.com](http://caniuse.com/#search=CustomEvent) and for IE11 it says:

> While a `window.CustomEvent` object exists, it cannot be called as a constructor. Instead of `new CustomEvent(...)`, you must use `e = document.createEvent('CustomEvent')` and then `e.initCustomEvent(...)`

Thus said, we could **make it work for IE11** (IE10 should be neglected in this case).

In Chrome v55 [Logdown's demo page](http://caiogondim.github.io/logdown.js/) works just fine for me. 😃

**Comment by caiogondim** [comment]
It should work now on IE11.

**Comment by SleepWalker** [comment]
it works after you refreshing the page with dev tools opened.

![bs_win10_ie_11 0](https://user-images.githubusercontent.com/2536916/31462131-3e31e3ea-aed4-11e7-99fb-5b366aac9882.jpg)
