### ISSUE TITLE
Showing Dates / Timestamps for log entries

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#43]
I really like the `logdown.js` project but does it support timestamps in front of log messages?

[We](https://wire.com/) are looking for something that can replace our current log library which gives us these features:

![unbenannt](https://cloud.githubusercontent.com/assets/469989/18949920/c34baff4-863d-11e6-94e3-38116296f064.PNG)

**Comment by caiogondim** [comment]
For timestamps in Chrome you can use this checkbox:
![sep-29-2016 13-49-43](https://cloud.githubusercontent.com/assets/33044/18953362/6086e79c-864e-11e6-8a61-420bd3f73f72.gif)

But that would work only in Chrome, not in other browsers or Node.js
We can implement this
Seems to be easy and straight forward

I'm thinking in an API similar to

```js
// Prints timestamp in the format `2016-08-13` or `YYYY-MM-DD`
const logger1 = new Logdown({
  prefix: 'lorem',
  timestamp: true
})

// If a string is passed, we use it as a template for formatting the timestamp
const logger2 = new Logdown({
  prefix: 'lorem',
  timestamp: 'MM/DD/YYYY'
})

// Throws an error in case we can't parse the string passed as template
const logger3 = new Logdown({
  prefix: 'lorem',
  timestamp: 'ipsum'
})
```

Thoughts?

**Comment by bennyn** [comment]
From the first view, I like having a date format like `'MM/DD/YYYY'`. One option I thought of is that `prefix` could accept also functions. Then people could write their own date mechanism, like:

```javascript
const logger = new Logdown({
  prefix: function() {
    var time = new Date().toLocaleString();
    return time + ' MyModule';
  }
});
```

**Comment by caiogondim** [comment]
Like both ideas
1. `prefix` should accept a function
2. Output timestamp behind a flag

You mind crating issues for both so we can work on it?

**Comment by bennyn** [comment]
I created the two issues:

1. https://github.com/caiogondim/logdown.js/issues/48
1. https://github.com/caiogondim/logdown.js/issues/49

From my side we can close down this issue here. WDYT?

**Comment by caiogondim** [comment]
Closing
