### ISSUE TITLE
Support logging objects

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#50]
With the Browser's console it's possible to log objects like:

``` javascript
var demo = new Logdown({
  prefix: 'demo',
  alignOuput: true
});

console.log('Hello World!', demo);
```

Which will result into this output:

![unbenannt](https://cloud.githubusercontent.com/assets/469989/19641923/35a63188-99e3-11e6-9b3b-60d48a7eb2a7.PNG)

**logdown.js** unfortunately stringifies objects, so that they cannot be accessed via the Browser's console:

![unbenannt](https://cloud.githubusercontent.com/assets/469989/19641955/5dfa5cb8-99e3-11e6-8b94-7f8ac595a1c3.PNG)

It would be nice if **logdown.js** treats objects like the standard JavaScript console does.

Here is some demo code:

``` javascript
var demo = new Logdown({
  prefix: 'demo',
  alignOuput: true
});

demo.log('Hello World!', demo);
```

**Comment by caiogondim** [comment]
Created a PR for it.
Can you review and merge if it's ok?

**Comment by bennyn** [comment]
Uuuuh, I am very eager to test it! Let me just wrap a few more Christmas presents for my family and then I will test it. 😃 🌈

**Comment by caiogondim** [comment]
No worries.
Frohe Weihnachten. 🎄 🎅
