### ISSUE TITLE
Maintain GitHub releases

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#53]
Current version of **logdown.js** is v1.3.1, but in the [GitHub releases](https://github.com/caiogondim/logdown.js/releases) we got stuck on v1.2.4. 

We should be in sync. 😃

**Comment by caiogondim** [comment]
Indeed
This is my bad

Care to fix it?

**Comment by bennyn** [comment]
We can have the gap which we have now but for any future release we should be in sync. So just close this issue if you agree. 😃
