### ISSUE TITLE
"alignOutput" doesn't work across different Logdown versions

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#63]
I have a webpacked module (`cryptobox.js`), which bundles my application together with Logdown.

In my main application I am loading this module and I am loading another Logdown via the `script` tag, to log inside my main application (because the bundled Logdown is not accessible from the outside).

Doing this I realized that the alignment is different:

![logdown](https://cloud.githubusercontent.com/assets/469989/21174512/e39385ee-c1dd-11e6-9d74-969f9297c00f.PNG)

Maybe it would be a good idea to allow `numbers` as values for `alignOutput`, so that you can set the spacing manually as a fallback. @caiogondim: WDYT?

Here is my code:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Demo</title>
    <link rel="shortcut icon" href="data:image/x-icon;" type="image/x-icon" />
    <script src="lib/dynamic/logdown/index.js"></script>
    <script src="bundle/wire-webapp-cryptobox.js"></script>
  </head>
  <body>
    <script>
      var storage = new cryptobox.store.IndexedDB('bundle_test');
      var box = new cryptobox.Cryptobox(storage, 10);

      box.init().then(function() {
        var logger = new Logdown({prefix: 'bundle_test', alignOutput: true});
        var fingerprint = box.identity.public_key.fingerprint();
        var message = 'Local Identity: ' + fingerprint;
        logger.log(message);
      });
    </script>
  </body>
</html>
```

**Comment by caiogondim** [comment]
I guess we should strive for simplicity.

Your use case seems odd for me.
You're using a bundle with Logdown and Logdown without a bundle?

Since you already have a bundle system and a Logdown inside the bundle, it's just a matter of exposing it globally.
Then you would share the same class.

I don't see value on having more than one class of Logdown in the same env.

**Comment by bennyn** [comment]
Ok, accepted. 😄
