### ISSUE TITLE
Rename "index.js" to "logdown.js"

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#65]
Logdown's output for Bower is called `index.js`. When people execute `bower install logdown`, they get an `index.js` file out of the box, which need to be included the following way:

```html
<script src="/bower_components/logdown/dist/index.js"></script>
```

I think it would be nicer to have:

```html
<script src="/bower_components/logdown/dist/logdown.js"></script>
```

Especially if you have a Bower copy task which just dumps all files from "bower_components" into a flat hierarchy. This way logdown would not overwrite another library (which also might use the name `index.js`).

Other very famous libraries (like boostrap) also use their name as output (in this case [bootstrap.js](https://github.com/twbs/bootstrap/blob/v4-dev/bower.json#L19)).

**Logdown's current output:**

![capture](https://cloud.githubusercontent.com/assets/469989/21420826/1792e0a8-c830-11e6-8698-8a20285c019c.PNG)

**Comment by lipis** [comment]
Makes more sense..

**Comment by caiogondim** [comment]
Agreed!
Care to make a PR?
