### ISSUE TITLE
The "prefixColor" should be configurable

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#66]
It should be possible to set a fixed color for a Markdown logger, like:

```javascript
var logger = new Logdown({
  alignOuput: true,
  prefix: 'cryptobox.store.IndexedDB',
  prefixColor: '#B58900'
});
```

**Comment by caiogondim** [comment]
Yes, makes a lot of sense.
The only caveat here is on supporting Node.
Don't think you can pass a HEX color to it.

**Comment by bennyn** [comment]
It would be also nice to have something like `prefixColor: false` to turn off colors completely. 

At [Wire](https://wire.com/) we use Selenium which tests our application and returns a log result of the JavaScript output from our test run. Because the log results can't show colors we get logs from Logdown like this:

```
"%ccryptobox.Cryptobox%c Trying to load Session with ID \"4683857e-38ac-44bb-b993-1848115e60f7@82450ccccb290bbd\" from cache..."
```

There are these `%c` characters which could be avoided if colors can be turned off in Logdown.

**Comment by caiogondim** [comment]
Makes sense as well.

My idea for this feature:

`prefixColor` should accept a HEX value.
The library should do the work to figure out the value on Node.

If `prefixColor === false`, we don't decorate it with color.
Should output the raw string.

Thoughts?

**Comment by bennyn** [comment]
You wrote exactly what I thought. 👍

**Comment by jamrizzi** [comment]
Nobody has fixed this yet??? I think I might do a pull request.

**Comment by bennyn** [comment]
@jamrizzi Please do, we would really appreciate that!! 😃

**Comment by caiogondim** [comment]
`prefixColor` now accepts HEX values for Node and browser.
Will work on a feature to disable completely decoration, in case you want to log to a file or a console without color support.

**Comment by jamrizzi** [comment]
Thanks :)

**Comment by bennyn** [comment]
@caiogondim is nailing it today! Great work. Thumbs up! 👍
