### ISSUE TITLE
Add different and extendable logging transports

### ISSUE THREAD

**Issue by bennyn** [caiogondim/logdown.js#68]
It would be nice if Logdown could write to log files. 

The [atma-logger](https://github.com/atmajs/atma-logger) for example is able to write to the filesystem or to a remote server (via HTTP): https://github.com/atmajs/atma-logger#transports

There is also [winston](https://github.com/winstonjs/winston), a multi-transport async logging library. With `winston` logging transports can be changed the following way:

```javascript
winston = require('winston');

winston.add(winston.transports.File, {
  filename: config.logging_file,
  handleExceptions: true,
})
.remove(winston.transports.Console)
.info('Name', 'Message');
```

Would be great to have something similar with Logdown. 😃

**Comment by caiogondim** [comment]
I like the idea a lot.

I would make as simple as possible, using an array that is a collection of functions that will be called on every `logdown` method.

```js
logdown.transports = []
```

My proposal for the API:

- Adding transport

```js
logdown.transports = logdown.transports.concat([
  (msg) => {
    console.log(msg)
  },
  (msg) => {
    fs.writeFile(filePath, msg)
  }
])
```

- Removing transport
```js
logdown.transports.splice(1, 1)
```

- List transports
```js
logdown.transports // => Array of functions
```

Don't think we should provide any custom transport function, since they are super easy to implement.

**Comment by SleepWalker** [comment]
@caiogondim Looks good, but it would be better to pass not only the formatted `msg`, but the raw one too, because the transports,won't most likely support all that cute coloring. The log level and logger instance name should be useful too.

Something like this:

```js
{
  msg,
  raw: [...args],
  level,
  instance
}
```

**Comment by caiogondim** [comment]
@SleepWalker Agreed!

Seems we are good to implement this.
Anyone up to it? @SleepWalker @bennyn 
We can pair if you fancy it.

**Comment by SleepWalker** [comment]
Ok, I can create PR.

One more thing about API. Would it better to make a method? Something like this:

```js
const unuse = logdown.transports.use(transport()); // e.g. express middleware style, or it can be push()
unuse();

// and alternative way to remove

const tr = transport();
logdown.transports.use(tr);
logdown.transports.unuse(tr);

// or even better

const removeTransport = logdown.addTransport(transport());
removeTransport();
```

I think the methods is better, because they hide implementation details and make code more flexible.

**Comment by caiogondim** [comment]
I like your idea, but what you're proposing IMHO is an interface similar to something we already have: Arrays.
I would make it super-simple, just an Array of objects.

**Comment by SleepWalker** [comment]
> I would make it super-simple, just an Array of objects.

Ok, I won't be arguing :) My point was, that mutation of public property is a little bit bad smell. I know, that this property is simple stupid, but nevertheless.

I, actually love the last syntax, because you do not traverse internals of the object isntance.

And one more thing, in your example, you are aware, that there are other transports beside the added one. And this things with slice... You can not guaranty, that the transport you've added is still at index 1 (however if you'll delegate transport removal to client code, you'll make your lib a little bit smaller).

**Comment by caiogondim** [comment]
> Ok, I won't be arguing :)
Nah, we are here to try to come up with the best idea :)

> My point was, that mutation of public property is a little bit bad smell. I know, that this property is simple stupid, but nevertheless.
We can use `get` and `set`, so it's transparent for users of the library.

> I, actually love the last syntax, because you do not traverse internals of the object instance.
And one more thing, in your example, you are aware, that there are other transports beside the added one. And this things with slice... You can not guaranty, that the transport you've added is still at index 1 (however if you'll delegate transport removal to client code, you'll make your lib a little bit smaller).
Def. It's a tradeoff. If we document it properly guess it's ok.
I would roll it as simple as possible, and create methods if needed.

**Comment by SleepWalker** [comment]
Ok. Let's try that :) Actually I was sold on the point, that the lib will be a little bit smaller. It is nice, when logging lib is lightweight

**Comment by bennyn** [comment]
Really happy to see that this issue get's an uplift! 😃 

For reference, here is how [winston](https://github.com/winstonjs/winston) does multi-transport handling:

```javascript
const winston = require('winston');

// Passing Transports in Configuration
const config = {
  transports: [
    new (winston.transports.Console)(),
    new (winston.transports.File)({filename: 'somefile.log'})
  ]
};

const logger = new winston.Logger(config);

// Adding / Removing Transports on the go
logger.add(winston.transports.File, {filename: 'somefile.log'});
logger.remove(winston.transports.Console);

// Adding / Removing Transports globally (for all upcoming logger instances)
winston.add(winston.transports.File, {filename: 'somefile.log'});
winston.remove(winston.transports.Console);
```

**Comment by SleepWalker** [comment]
Hi, I've created #93. Please look if it is ok.
I've also fixed a bug, where you have created facade around non-function properties of logger

**Comment by SleepWalker** [comment]
One more thing. As for now, I'm calling transports only if `state.isEnabled === true`, but in reality you, probably, need a little bit different behavior. On production I'd probably need:

* disable console output, but with an opportunity to enable it, when I need to debug
* use transport, to forward all `error` and `warn` to e.g. sentry, disregarding whether the console output is on

To achieve this, we must call transports before [isEnabled check](https://github.com/caiogondim/logdown.js/pull/93/files#diff-d7e697eff3913f1acaacac8002c3b05eR98). @caiogondim what do you thing about this?

**Comment by caiogondim** [comment]
IMHO, If an instance is disabled, we should make it "dorment".
Doing the opposite would make it confusing.

I can see that use case being common as well.
For that I would propose monkey-patching the logger methods.

```js

logger.state.isEnabled // => true

if (production) {
  logger
    .filter(prop => typeof prop === 'function')
    .forEach(method => logger[method] = () => {})
}

// All transports would still be enabled
```

**Comment by SleepWalker** [comment]
we could pass isEnabled as an additional prop in transport and the the transport may look like this:

```js
function transport({msg, level, isEnabled, args}) {
  if (!isEnabled) {
    // we dont care, but we can use this if we want
  }

  if (['warn', 'error'].includes(level)) {
    raven[level](msg, args[1]);
  }
}
```

or we can allow extended configs for transports, e.g.:

```js
logdown.transports = [{
  isEnabled: true, // optional boolean|function, default: true (or === state.isEnabled to avoid confusion)
  levels: /error|warn/, // default: /.+/
  instances: /foo/, // default: /.+/ (don't know, whether it is useful)
  transport: transport
}];

// or
logdown.transports = [transport]; // log all levels. isEnabled: true
```

the usage of `function` for isEnabled may allow dynamically on/off loggers. But this is probably overkill and won't be useful in real applications.

btw. I've forgot, that loggers like raven expect message + some context. In the opposite logdown expects any number of args. This means, that `msg` prop for transport may be a little bit useless for such integrations... or we can generate it like `'[' + instance + '] ' + args.filter((arg) => typeof arg !== 'object').join(' ')`

**Comment by SleepWalker** [comment]
A little bit more thoughts:

* For debug (in dev or prod env) you want to be able to enable logging in console and optionally control verbosity through instance filters.
* For production logging you want the logging to be on, even if there is nothing set in localStorage or NODE_DEBUG. But you want to restrict logging to some specific levels (warn, error, etc)

Levels you can currently control in transport function (I'm talking about the that currently in PR, without my comment above). But to enable the actual logging, you will be forced to hard code isEnabled to always be true, which will spam the console with debug messages, that are not supposed to be shown for everyone on production.

**Comment by caiogondim** [comment]
If you want to control which methods should print or not, you should monkey-patch since it's not the default behavior: https://github.com/caiogondim/logdown.js/blob/master/doc/faq.md#disabling-one-method-on-an-instance-at-runtime

Is that what you meant?

**Comment by SleepWalker** [comment]
The point form FAQ is not enough flexible. We won't be able to control levels depending on transport. I think, that this is quite important thing for transports feature.

We can delegate levels filtering to transport function (actually, it is currently delegated in my PR), but in order to allow full transport control we need delegate `isEnabled` too (see the first snippet in my previous comment). This is the simplest, flexiblest and the most compact implementation possible.

To provide a declarative api with defaults (like in the second snippet), there should be implemented a method to add/remove transports, because we need a logic, that will normalize transport definitions and fill defaults.

---

btw. in my project I have a wrapper around your lib, which gives me an ability to implement transports and everything that I want without monkey-patching. This also allows switching between logging libs, without touching any client code (because it actually using a wrapper instead of directly logdown). What is cool to is that localStorage or NODE_DEBUG will affect only console output and transports are still working.

**Comment by caiogondim** [comment]
Like your idea of passing `isEnabled` as an argument.
For better extensibility, I would pass the whole `state` from (which today has only `isEnabled`.


```js
function transport({msg, level, args, state}) {
  if (!state.isEnabled) {
    // we dont care, but we can use this if we want
  }

  if (['warn', 'error'].includes(level)) {
    raven[level](msg, args[1]);
  }
}
```

**Comment by SleepWalker** [comment]
I've pushed all the updates and readme into the #93

**Comment by caiogondim** [comment]
Replicating here what I said on #93.
We need to push a new version. It's a minor version since we (you) added a new feature with backward compatibility 🎉 

What's your npm username?

**Comment by SleepWalker** [comment]
@caiogondim the same as here, but lowercased **sleepwalker** (https://www.npmjs.com/~sleepwalker)

**Comment by caiogondim** [comment]
Just added you on npm.
You have publishing rights now.

To publish we run the tests, and then:
```
npm version minor
npm publish
```

Then we need to make a release on GitHub as well.

Let me know if you need some help.

And welcome to the team 🎉

**Comment by caiogondim** [comment]
Just removed some ES6 from the code, since it was breaking older browsers.

**Comment by SleepWalker** [comment]
Ok. Thank you. I'll look at the evening.

BTW. Would it better to add Babel? And what browsers do we support?

**Comment by bennyn** [comment]
@SleepWalker **Great contribution!** Thanks for your efforts and welcome to the team! :tada: 
I sent you an email. Maybe we can meet over a beer in Kiev. 🍻 😃

**Comment by caiogondim** [comment]
> BTW. Would it better to add Babel? And what browsers do we support?

The reasoning for not adding babel is the same for TypeScript: bundle size
This is a small lib, don't think we would benefit a lot using Babel.

**Comment by caiogondim** [comment]
@SleepWalker Waiting for your release to merge https://github.com/caiogondim/logdown.js/pull/97 😄

**Comment by caiogondim** [comment]
@SleepWalker Sorry, I had to push a new release because of a crazy bug on Samsung Browser that was breaking on staging at the office 😢 

https://github.com/caiogondim/logdown.js/releases/tag/v3.2.0

**Comment by SleepWalker** [comment]
Oh, it's okay :+1:
I'll add new commits :D

**Comment by caiogondim** [comment]
Do it :)
Just ping me if you need some help.
