### ISSUE TITLE
could you change the name about the minified file

### ISSUE THREAD

**Issue by kennynaoh** [caiogondim/logdown.js#79]
Hello @caiogondim I am the member of cdnjs project. We want to host this library. I found that there is a file `logdown.js`. Could you want to change the name to `logdown.min.js`? Thanks!

https://github.com/cdnjs/cdnjs/issues/10272

**Comment by caiogondim** [comment]
Guess we should deliver a normal and minified version:
- `logdown.js`: not minified
- `logdown.min.js`: minified

@bennyn What you think?

**Comment by bennyn** [comment]
Yupp! Let's provide a `.js` and a `.min.js` (with `uglify`). Thanks @kennynaoh for reaching out to us!

**Comment by kennynaoh** [comment]
Thank you guys, let me know if it has a correct naming scheme.

**Comment by bennyn** [comment]
@caiogondim We also need to make sure that our `bower.json` file points to the unminified version (https://github.com/bower/spec/blob/master/json.md#main) because currently it points to the minified version which is against the Bower guidelines: "Do not include minified files".

**Comment by bennyn** [comment]
@kennynaoh We got it! :) https://github.com/caiogondim/logdown.js/tree/master/dist

**Comment by caiogondim** [comment]
@kennynaoh Let's know when you have `logdown` on your CDN, so we can make some PR about it as well 😄
