### ISSUE TITLE
Logging levels

### ISSUE THREAD

**Issue by aboyer1013** [caiogondim/logdown.js#82]
Would like to have the ability to toggle logging based on level.

```
var logger = new Logdown({prefix: 'namespace'});
// Only log errors and warnings
logger.disable('namespace');
logger.error.enable('namespace');
logger.warn.enable('namespace');
```

**Comment by ataft** [comment]
I really need this too. Maybe add 'trace', and then follow the same order as the loglevel api. Perhaps it would look something like this:

//Globally for all prefixes
logdown.setLevel('info');

//for a single prefix
const logger = logdown({ prefix: 'foo', level: 'info' });

**Comment by caiogondim** [comment]
### To disable methods per instance:
```js
const logger = new Logdown({ prefix: 'lorem' })

// Disabling
logger.warn = function() {}

// Reenabling
logger.warn = Logdown.prototype.warn
```

**Comment by caiogondim** [comment]
I don't think we need more API for this.
But, at the same time, we think we should have documentation for  common scenarios like this.

**Comment by caiogondim** [comment]
Done: https://github.com/caiogondim/logdown.js/blob/master/readme.md#recipes

**Comment by caiogondim** [comment]
@ataft I will add the `trace` method as well.

**Comment by caiogondim** [comment]
Since it can be done with pure JS, I will close this issue.

**Comment by ataft** [comment]
Perfect, thanks!
