### ISSUE TITLE
Support redux-logger

### ISSUE THREAD

**Issue by caiogondim** [caiogondim/logdown.js#84]
Currently logdown cannot be used with [redux-logger](https://github.com/evgenyrodionov/redux-logger)

**Comment by michaelzoidl** [comment]
Its not that hard, just make a new middleware for redux and log the action (or whatever you want log, just grab the info you get by the middleware.

```js
import logdown from 'logdown'
const logger = logdown('debug')

const LogdownReduxMiddleware = store => next => action => {
  logger.log('dispatch', action)
  return next(action)
}
```

And the add it to the `applyMiddleware` part
```js
const store = applyMiddleware(
  LogdownReduxMiddleware
)(createStore)
```

**Comment by caiogondim** [comment]
Indeed. Im closing this thread as I'm more willing to create a redux logger myself.
