### ISSUE TITLE
Logging only an object doesn't display correctly

### ISSUE THREAD

**Issue by ataft** [caiogondim/logdown.js#88]
For example, the following two lines result in the image below (Browser: Chrome 57.0.2987.133):
```
     logdown('main').log({hello:'world'});
     logdown('main').log('main',{hello:'world'});

```
![image](https://cloud.githubusercontent.com/assets/11670864/25505222/bd973066-2b55-11e7-880f-4d0c3cbd1274.png)

**Comment by caiogondim** [comment]
I thought I have fixed that.
It's fixed on a branch I have for v3.
When I upload it I will update it here as well.

**Comment by gregjmcdonald** [comment]
+1

**Comment by caiogondim** [comment]
This was fixed on v3
