### ISSUE TITLE
Script cannot run due to "unsafe-eval" when CSP security directives are set.

### ISSUE THREAD

**Issue by aga5tya** [caiogondim/logdown.js#89]
First off,, nice library you got here for logging needs. 👍 

I have an issue, probably related to only my scenario, since i have CSP directives that avoid unnecessary eval, the below part of the code doesn't execute and library doesn't load.
https://github.com/caiogondim/logdown.js/blob/master/src/util/get-global.js#L4

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'
```
Any specific reason why eval was chosen to get the global window object? I saw the blame history and it was along jest fixes?

**Comment by caiogondim** [comment]
The library works for the browser and Node.
That was a hacky way to always get the global object on both envs.

But happy to change it if you have a better idea.

**Comment by caiogondim** [comment]
v3.0.1 released
https://www.npmjs.com/package/logdown
