### ISSUE TITLE
Safari not working

### ISSUE THREAD

**Issue by patrickpietens** [caiogondim/logdown.js#95]
Hey guys,

I love logdown.js and I use it a lot in my project. I just upgraded to the latest version. But unfortunately it isn't working anymore in Safari. 

Opening https://caiogondim.github.io/logdown.js/ in Safari shows the following error:
```
TypeError: demo.log is not a function. (In 'demo.log('Devtools was open')', 'demo.log' is undefined)
```

**Comment by caiogondim** [comment]
Thanks for the bug report, Patrick. 
I’m travelling right now and will take a look on it tomorrow at home. 
Should be a simple fix.

**Comment by patrickpietens** [comment]
No problem at all! And take your time. I appreciate the time and effort you put into the project. And let me know if I can help.

Btw.
I'm using version 3.0.2 for now. Which is working.

**Comment by caiogondim** [comment]
I was testing the URL `https://caiogondim.github.io/logdown.js/` in Safari v11 on macOS and it works fine for me.
What platform are you testing in?

**Comment by patrickpietens** [comment]
I'm still on Safari Version 9.1.2 (11601.7.7). I didn't want to update because of Wacom/Sierra problems. So maybe it's not worth your time to invest in this bug. Or I can have a look at it later. Let me know.

**Comment by caiogondim** [comment]
It should work on Safari 9 as well.
Since I don't have an old Safari here,I will take a look on IE11, it might be broken there as well.

**Comment by patrickpietens** [comment]
@caiogondim Let me know if I can help

**Comment by caiogondim** [comment]
Can you retry running https://caiogondim.github.io/logdown.js/ on your Safari?
I removed ES6 code.

**Comment by patrickpietens** [comment]
Still getting the same error 😞 I'm in a middle of a release right now. But I will have a look at the code later and do a PR to fix this issue.

![screen shot 2017-10-09 at 22 38 48](https://user-images.githubusercontent.com/132625/31357602-b49efe66-ad42-11e7-9425-172d6e8623d9.png)

Thnx for your time and effort so far.

**Comment by caiogondim** [comment]
Try again.
I deleted a lib to detect if devtools was open or not.
Was causing an infinite loop on IE11.

http://caiogondim.github.io/logdown.js/

**Comment by caiogondim** [comment]
It's working on IE11 now.

**Comment by patrickpietens** [comment]
Still no luck 😞 

Like I said, I can help you somewhere next week. And thnx again for the time and effort. I really appreciate it and I know how annoying it can be when someone keeps telling you something still not working. Sorry for being that person.

Btw. 
As an os contributor you can get a free browserstack account 👍

**Comment by caiogondim** [comment]
That would be nice.

It should be a silly mistake that we can patch.
If you can send me a stack trace I should be able to send a fix.

**Comment by caiogondim** [comment]
Guess I fixed that.
Just waiting a release to merge the PR https://github.com/caiogondim/logdown.js/pull/97

**Comment by caiogondim** [comment]
I was able to reproduce with an old Android.

**Comment by caiogondim** [comment]
Guess I fixed your bug.
Can you try to replicate again?

**Comment by caiogondim** [comment]
Made a new release: https://github.com/caiogondim/logdown.js/releases/tag/v3.2.0

**Comment by patrickpietens** [comment]
@caiogondim It works!!!!!1 Thnx mate <3
